/*VOLVER TODO A CERO, BORRAR BASE DE DATOS Y USUARIO (SE DEBERÍA EJECUTAR COMO ROOT)*/
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'student'@'localhost';
DROP USER IF EXISTS 'student'@'localhost';
DROP DATABASE IF EXISTS students_db_3;